"""schema refine: jsonb intake_log, datetime reminder_event, composite indexes

Revision ID: 1505183d9bb0
Revises: eb96ebb184ba
Create Date: 2026-05-26 15:36:29.243055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1505183d9bb0'
down_revision: Union[str, Sequence[str], None] = 'eb96ebb184ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ddinter_interaction_drug_a_b', 'ddinter_interaction', ['drug_a_id', 'drug_b_id'], unique=False)
    op.create_index('ix_ddinter_interaction_drug_b_a', 'ddinter_interaction', ['drug_b_id', 'drug_a_id'], unique=False)
    op.alter_column('intake_log', 'drugs',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='drugs::jsonb')
    op.alter_column('intake_log', 'foods',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='foods::jsonb')
    op.create_index('ix_intake_log_elder_created', 'intake_log', ['elder_id', 'created_at'], unique=False)
    op.alter_column('reminder_event', 'due_at',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using='due_at::timestamp')
    op.alter_column('reminder_event', 'completed_at',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using='completed_at::timestamp')
    op.create_index('ix_reminder_event_elder_status_due', 'reminder_event', ['elder_id', 'status', 'due_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reminder_event_elder_status_due', table_name='reminder_event')
    op.alter_column('reminder_event', 'completed_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True,
               postgresql_using='completed_at::text')
    op.alter_column('reminder_event', 'due_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               postgresql_using='due_at::text')
    op.drop_index('ix_intake_log_elder_created', table_name='intake_log')
    op.alter_column('intake_log', 'foods',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True,
               postgresql_using='foods::text')
    op.alter_column('intake_log', 'drugs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True,
               postgresql_using='drugs::text')
    op.drop_index('ix_ddinter_interaction_drug_b_a', table_name='ddinter_interaction')
    op.drop_index('ix_ddinter_interaction_drug_a_b', table_name='ddinter_interaction')
    # ### end Alembic commands ###
