"""init schema

Revision ID: eb96ebb184ba
Revises: 
Create Date: 2026-05-25 19:54:30.406533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb96ebb184ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ddinter_drug',
    sa.Column('drug_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drug_name', sa.String(length=256), nullable=False),
    sa.Column('drug_name_normalized', sa.String(length=256), nullable=True),
    sa.Column('atc_code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('drug_id')
    )
    op.create_index(op.f('ix_ddinter_drug_drug_name'), 'ddinter_drug', ['drug_name'], unique=False)
    op.create_index(op.f('ix_ddinter_drug_drug_name_normalized'), 'ddinter_drug', ['drug_name_normalized'], unique=False)
    op.create_table('ddinter_interaction',
    sa.Column('interaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drug_a_id', sa.Integer(), nullable=False),
    sa.Column('drug_b_id', sa.Integer(), nullable=False),
    sa.Column('drug_a_name', sa.String(length=256), nullable=False),
    sa.Column('drug_b_name', sa.String(length=256), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.create_table('elder_profile',
    sa.Column('elder_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('diseases', sa.Text(), nullable=True),
    sa.Column('health_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('elder_id')
    )
    op.create_table('intake_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elder_id', sa.String(length=64), nullable=False),
    sa.Column('drugs', sa.Text(), nullable=True),
    sa.Column('foods', sa.Text(), nullable=True),
    sa.Column('recognized_text', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('risk_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['elder_id'], ['elder_profile.elder_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('medication_plan',
    sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elder_id', sa.String(length=64), nullable=False),
    sa.Column('drug_name', sa.String(length=256), nullable=False),
    sa.Column('dosage', sa.String(length=128), nullable=True),
    sa.Column('frequency', sa.String(length=128), nullable=True),
    sa.Column('time_of_day', sa.String(length=128), nullable=True),
    sa.Column('with_meal', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['elder_id'], ['elder_profile.elder_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('reminder_rule',
    sa.Column('rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elder_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('schedule_time', sa.String(length=8), nullable=True),
    sa.Column('repeat_pattern', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['elder_id'], ['elder_profile.elder_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('reminder_event',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('elder_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('due_at', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['elder_id'], ['elder_profile.elder_id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['reminder_rule.rule_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_event')
    op.drop_table('reminder_rule')
    op.drop_table('medication_plan')
    op.drop_table('intake_log')
    op.drop_table('elder_profile')
    op.drop_table('ddinter_interaction')
    op.drop_index(op.f('ix_ddinter_drug_drug_name_normalized'), table_name='ddinter_drug')
    op.drop_index(op.f('ix_ddinter_drug_drug_name'), table_name='ddinter_drug')
    op.drop_table('ddinter_drug')
    # ### end Alembic commands ###
